name: Update Epoch Log

# 1) Tell the robot when to wake up:
on:
  schedule:
    - cron: '*/5 * * * *'   # every 10 minutes
  workflow_dispatch:        # also let us press a “Run” button by hand

jobs:
  update-log:
    runs-on: ubuntu-latest  # the robot uses an Ubuntu computer

    steps:
      # Step A: fetch our code
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      # Step B: set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step C: run the script
      - name: Run epoch script once
        run: |
          python epoch_curses_dashboard.py --once --output docs/epoch_dashboard_log.md

      # Step D: commit any changes
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/epoch_dashboard_log.md
          git commit -m "Update epoch log" || echo "No changes to commit"
          git push
