name: Update Epoch Log

on:
  schedule:
    - cron:  '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-log:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install windows-curses win10toast || true

      - name: Run epoch script
        run: |
          python epoch-dashboard.py --once --output docs/epoch_dashboard_log.md

      - name: Commit & push (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/epoch_dashboard_log.md
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update epoch log"
            git pull --rebase origin main
            git push
          fi
