name: Update Epoch Log

on:
  schedule:
    - cron: '*/5 * * * *'  # every 10 minutes
  workflow_dispatch:      # manual trigger

jobs:
  update-log:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # allow pushing back using the GITHUB_TOKEN
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install windows-curses win10toast || true

      - name: Run epoch script once
        run: |
          python epoch-dashboard.py --once --output docs/epoch_dashboard_log.md

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/epoch_dashboard_log.md
          git commit -m "Update epoch log" || echo "No changes to commit"
          git push
